<?php
$data = array (
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '醋',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 0,
    'id' => '66',
    'name' => '醋',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '酱油',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 0,
    'id' => '67',
    'name' => '酱油',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '调味品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 0,
    'id' => '50',
    'name' => '调味品',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '火锅/香锅料',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '68',
    'name' => '火锅/香锅料',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '料酒',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '75',
    'name' => '料酒',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '腐乳',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '72',
    'name' => '腐乳',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '调味酱',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '69',
    'name' => '调味酱',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '酱菜',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '71',
    'name' => '酱菜',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '盐',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '76',
    'name' => '盐',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '鸡精/味精',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '73',
    'name' => '鸡精/味精',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '糖',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '70',
    'name' => '糖',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '调味汁',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '74',
    'name' => '调味汁',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '调味料',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '调味料',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '12',
    'goods_num' => 0,
    'level' => 0,
    'id' => '51',
    'name' => '食用油',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '核桃油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '83',
    'name' => '核桃油',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '亚麻籽油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '80',
    'name' => '亚麻籽油',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '大豆油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '78',
    'name' => '大豆油',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '杏仁油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '84',
    'name' => '杏仁油',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '稻米油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '81',
    'name' => '稻米油',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '橄榄油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => '橄榄油',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '花生油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '77',
    'name' => '花生油',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '葡萄籽油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '82',
    'name' => '葡萄籽油',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '油菜籽油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '79',
    'name' => '油菜籽油',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '葵花籽油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '60',
    'name' => '葵花籽油',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '玉米油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '61',
    'name' => '玉米油',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '调和油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '62',
    'name' => '调和油',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '86',
    'name' => '方便速食',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '速食汤/粥',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '89',
    'name' => '速食汤/粥',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '罐头',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => '罐头',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '火腿肠',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '88',
    'name' => '火腿肠',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '米面杂粮',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '85',
    'name' => '米面杂粮',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '杂粮',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '93',
    'name' => '杂粮',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '大米',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '90',
    'name' => '大米',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '面粉',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '91',
    'name' => '面粉',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '挂面',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '92',
    'name' => '挂面',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '厨房用具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '52',
    'name' => '厨房用具',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '茶具',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '96',
    'name' => '茶具',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '137',
    'name' => '其他',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '茶叶罐',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '134',
    'name' => '茶叶罐',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '茶杯',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '131',
    'name' => '茶杯',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '茶具配件',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '135',
    'name' => '茶具配件',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '茶壶',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '132',
    'name' => '茶壶',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '茶宠摆件',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '茶宠摆件',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '茶盘茶托',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '133',
    'name' => '茶盘茶托',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '整套茶具',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '130',
    'name' => '整套茶具',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '水具酒具',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '94',
    'name' => '水具酒具',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '陶瓷/马克杯',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '121',
    'name' => '陶瓷/马克杯',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '塑料杯',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '118',
    'name' => '塑料杯',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '保温杯',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '122',
    'name' => '保温杯',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '运动水壶',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '119',
    'name' => '运动水壶',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '酒杯/酒具',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '123',
    'name' => '酒杯/酒具',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '玻璃杯',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '120',
    'name' => '玻璃杯',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '杯具套装',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '124',
    'name' => '杯具套装',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '95',
    'name' => '餐具',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '一次性用品',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '128',
    'name' => '一次性用品',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '餐具套装',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '125',
    'name' => '餐具套装',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '果盘/果筐',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '129',
    'name' => '果盘/果筐',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '碗/碟/盘',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '126',
    'name' => '碗/碟/盘',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '筷勺/刀叉',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '127',
    'name' => '筷勺/刀叉',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '烹饪锅具',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 1,
    'id' => '63',
    'name' => '烹饪锅具',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '水壶',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '105',
    'name' => '水壶',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '奶锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '奶锅',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '压力锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '99',
    'name' => '压力锅',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '火锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '火锅',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '锅具套装',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '锅具套装',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '蒸锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '100',
    'name' => '蒸锅',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '炒锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '97',
    'name' => '炒锅',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '煲类',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '煲类',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '汤锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '101',
    'name' => '汤锅',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '煎锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '98',
    'name' => '煎锅',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '刀剪菜板',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '64',
    'name' => '刀剪菜板',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '多功能刀',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '112',
    'name' => '多功能刀',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '刀具套装',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '109',
    'name' => '刀具套装',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '砧板',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '110',
    'name' => '砧板',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '菜刀',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '菜刀',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '瓜果刀/刨',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '111',
    'name' => '瓜果刀/刨',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '剪刀',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '108',
    'name' => '剪刀',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '厨房配件',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '65',
    'name' => '厨房配件',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '饭盒/提锅',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '115',
    'name' => '饭盒/提锅',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '储物/置物架',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '116',
    'name' => '储物/置物架',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '保鲜盒',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '113',
    'name' => '保鲜盒',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '小工具',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '117',
    'name' => '小工具',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '烘培/烧烤',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '114',
    'name' => '烘培/烧烤',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '差价',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 0,
    'id' => '138',
    'name' => '差价',
  ),
);
?>