<?php
$data = array (
  0 => 
  array (
    'cat_id' => '66',
    'cat_name' => '醋',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  1 => 
  array (
    'cat_id' => '67',
    'cat_name' => '酱油',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  2 => 
  array (
    'cat_id' => '50',
    'cat_name' => '调味品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '51',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '12',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '86',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '85',
    'cat_name' => '米面杂粮',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '52',
    'cat_name' => '厨房用具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '138',
    'cat_name' => '差价',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  8 => 
  array (
    'cat_id' => '68',
    'cat_name' => '火锅/香锅料',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '75',
    'cat_name' => '料酒',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '72',
    'cat_name' => '腐乳',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '69',
    'cat_name' => '调味酱',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '71',
    'cat_name' => '酱菜',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '76',
    'cat_name' => '盐',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '73',
    'cat_name' => '鸡精/味精',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '70',
    'cat_name' => '糖',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '74',
    'cat_name' => '调味汁',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '54',
    'cat_name' => '调味料',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '83',
    'cat_name' => '核桃油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '80',
    'cat_name' => '亚麻籽油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '78',
    'cat_name' => '大豆油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '84',
    'cat_name' => '杏仁油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '81',
    'cat_name' => '稻米油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '59',
    'cat_name' => '橄榄油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '77',
    'cat_name' => '花生油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '82',
    'cat_name' => '葡萄籽油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '79',
    'cat_name' => '油菜籽油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '60',
    'cat_name' => '葵花籽油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '61',
    'cat_name' => '玉米油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '62',
    'cat_name' => '调和油',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '96',
    'cat_name' => '茶具',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '94',
    'cat_name' => '水具酒具',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '95',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '63',
    'cat_name' => '烹饪锅具',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '64',
    'cat_name' => '刀剪菜板',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '65',
    'cat_name' => '厨房配件',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '105',
    'cat_name' => '水壶',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '102',
    'cat_name' => '奶锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '99',
    'cat_name' => '压力锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '106',
    'cat_name' => '火锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '103',
    'cat_name' => '锅具套装',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '100',
    'cat_name' => '蒸锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '97',
    'cat_name' => '炒锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '104',
    'cat_name' => '煲类',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '101',
    'cat_name' => '汤锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '98',
    'cat_name' => '煎锅',
    'measure_unit' => '',
    'parent_id' => '63',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '112',
    'cat_name' => '多功能刀',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '109',
    'cat_name' => '刀具套装',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '110',
    'cat_name' => '砧板',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '107',
    'cat_name' => '菜刀',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '111',
    'cat_name' => '瓜果刀/刨',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '108',
    'cat_name' => '剪刀',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '115',
    'cat_name' => '饭盒/提锅',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '116',
    'cat_name' => '储物/置物架',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '113',
    'cat_name' => '保鲜盒',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '117',
    'cat_name' => '小工具',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '114',
    'cat_name' => '烘培/烧烤',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '93',
    'cat_name' => '杂粮',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '90',
    'cat_name' => '大米',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '91',
    'cat_name' => '面粉',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '92',
    'cat_name' => '挂面',
    'measure_unit' => '',
    'parent_id' => '85',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '89',
    'cat_name' => '速食汤/粥',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '87',
    'cat_name' => '罐头',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '88',
    'cat_name' => '火腿肠',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '121',
    'cat_name' => '陶瓷/马克杯',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '118',
    'cat_name' => '塑料杯',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '122',
    'cat_name' => '保温杯',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '119',
    'cat_name' => '运动水壶',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '123',
    'cat_name' => '酒杯/酒具',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '120',
    'cat_name' => '玻璃杯',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '124',
    'cat_name' => '杯具套装',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '128',
    'cat_name' => '一次性用品',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '125',
    'cat_name' => '餐具套装',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '129',
    'cat_name' => '果盘/果筐',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '126',
    'cat_name' => '碗/碟/盘',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '127',
    'cat_name' => '筷勺/刀叉',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  76 => 
  array (
    'cat_id' => '137',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '134',
    'cat_name' => '茶叶罐',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '131',
    'cat_name' => '茶杯',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  79 => 
  array (
    'cat_id' => '135',
    'cat_name' => '茶具配件',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '132',
    'cat_name' => '茶壶',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  81 => 
  array (
    'cat_id' => '136',
    'cat_name' => '茶宠摆件',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  82 => 
  array (
    'cat_id' => '133',
    'cat_name' => '茶盘茶托',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  83 => 
  array (
    'cat_id' => '130',
    'cat_name' => '整套茶具',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>