<?php
$data = array (
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '蔬菜水果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '蔬菜水果',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '蔬菜',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '11',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '蔬菜',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '豆角类',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '31',
    'name' => '豆角类',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '叶菜类',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '32',
    'name' => '叶菜类',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '根茎类',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '33',
    'name' => '根茎类',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '茄果类',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '34',
    'name' => '茄果类',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '香辛类*葱姜',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '54',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '36',
    'name' => '香辛类*葱姜',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '菌菇类',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '55',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '37',
    'name' => '菌菇类',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '速冻蔬菜',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '56',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '38',
    'name' => '速冻蔬菜',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '香料类',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '57',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '39',
    'name' => '香料类',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '每日鲜蔬菜',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '58',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '41',
    'name' => '每日鲜蔬菜',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '花菜类',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '58',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '40',
    'name' => '花菜类',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '礼盒',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '59',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '42',
    'name' => '礼盒',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '水果',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '水果',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '台湾水果',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '43',
    'name' => '台湾水果',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '国产水果',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '44',
    'name' => '国产水果',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '速冻水果',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '45',
    'name' => '速冻水果',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '进口水果',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '46',
    'name' => '进口水果',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '水果礼盒',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '54',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '47',
    'name' => '水果礼盒',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '肉禽蛋品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '肉禽蛋品',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '水产海鲜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '水产海鲜',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '母婴童',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '母婴童',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '瓜类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '54',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '35',
    'name' => '瓜类',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '奶制品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '54',
    'has_children' => '0',
    'goods_num' => '75',
    'level' => 0,
    'id' => '18',
    'name' => '奶制品',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '粮油副食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '55',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '粮油副食',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '56',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '24',
    'name' => '休闲食品',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '酒水茶饮',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '57',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '25',
    'name' => '酒水茶饮',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '熟食面点',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '58',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '26',
    'name' => '熟食面点',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '有机食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '28',
    'name' => '有机食品',
  ),
);
?>